obj: airl
IS: false
seed: 23
cuda: -1

env:
  env_name: Ant-v2
  T: 1000
  state_indices: all

# AIRL专用参数
airl:
  total_timesteps: 4000000  # AIRL训练总步数，约500轮
  expert_episodes: 16       # 专家轨迹数量，与BC保持一致
  eval_episodes: 20         # 评估episode数
  demo_batch_size: 2048     # 演示数据批大小
  gen_replay_buffer_capacity: 4096  # 生成器replay buffer容量
  n_disc_updates_per_round: 8       # 每轮判别器更新次数
  n_envs: 4                         # 并行环境数
  reward_hid_sizes: [256, 256]      # 奖励网络隐藏层大小

# PPO学习器参数
ppo:
  batch_size: 256           
  learning_rate: 0.0003     
  gamma: 0.99               
  clip_range: 0.2           
  ent_coef: 0.01            
  vf_coef: 0.5              
  n_epochs: 10              

# 评估参数
eval:
  episodes: 20
  deterministic: true
